#!/bin/bash

set -ueo pipefail

if ! [[ "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" = "master" ]]; then
	echo -e "Skipping site push (TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_BRANCH=$TRAVIS_BRANCH)\n"
	exit 0
fi

aws s3 sync . s3://appropriate.io --acl public-read --delete --exclude '.git/*' --exclude '.cache/*'
